CREATE TABLE IF NOT EXISTS UserPrivacyPreference (
  id TEXT PRIMARY KEY NOT NULL,
  userId TEXT UNIQUE NOT NULL,
  showActivityToGroup INTEGER NOT NULL DEFAULT 1,
  showGameStatus INTEGER NOT NULL DEFAULT 1,
  showRatings INTEGER NOT NULL DEFAULT 1,
  showNotes INTEGER NOT NULL DEFAULT 0,
  showOnlineStatus INTEGER NOT NULL DEFAULT 1,
  allowGroupInvites INTEGER NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UserPrivacyPreference_userId_fkey FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);
